spring:
  application:
    name: admin

  redis:
    password: VMoEXKYYAwb6ykzg
    database: 0
    port: 6379
    jedis:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: 200
        max-wait: -1
    host: 82.157.8.205
    timeout: 1000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fluxpay?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 314159
    #???????druid
    type: com.alibaba.druid.pool.DruidDataSource
    #??????
    druid.initial-size: 10
    #?????
    druid.min-idle: 100
    #?????
    druid.max-active: 1000
    #????????????????
    druid.max-wait: 60000
    #????????
    druid.validation-query: SELECT 1 FROM DUAL
    druid.test-on-borrow: false
    druid.test-on-return: false
    #?????????
    druid.test-while-idle: true
    #???????????????????????????????
    druid.time-between-eviction-runs-millis: 60000
    # ??????????????????????
    druid.min-victable-idle-time-millis: 300000
    #?????? ?????
    druid.query-timeout: 60000
    #??????
    #druid.keep-alive: true
    # ??connectProperties?????mergeSql????SQL??:???
    druid.connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
